### ISSUE TITLE
Settings file not found

### ISSUE THREAD

**Issue by danielgrahl** [janhaag/PSE2011#1]
I get the following exception upon exiting the program (on Linux x32). A file named .psesettings does not exist.

java.io.IOException: No such file or directory
    at java.io.UnixFileSystem.createFileExclusively(Native Method)
    at java.io.File.createNewFile(File.java:900)
    at misc.Settings.saveSettings(Settings.java:127)
    at gui.MainFrame.openWindow(MainFrame.java:243)
    at gui.controller.MainController.initMainFrame(MainController.java:54)
    at gui.controller.MainController.<init>(MainController.java:47)
    at misc.MainClass.main(MainClass.java:18)

**Comment by janhaag** [comment]
I can't reproduce this on Linux 3.0.0-16-generic #29-Ubuntu SMP x86_64 (Ubuntu 11.10 w/ prerelease channel active)

EDIT: It's probably a problem with the Settings class.

**Comment by danielgrahl** [comment]
Not reproducible in the current version.
