### ISSUE TITLE
NullPointerException in SMTLibTranslator

### ISSUE THREAD

**Issue by danielgrahl** [janhaag/PSE2011#10]
Happens sometimes when I press "validate".

java.lang.NullPointerException
        at verifier.smtlib.SMTLibTranslator.visit(SMTLibTranslator.java:428)
        at ast.FunctionCall.accept(FunctionCall.java:37)
        at verifier.smtlib.SMTLibTranslator.visit(SMTLibTranslator.java:414)
        at ast.LogicalExpression.accept(LogicalExpression.java:69)
        at verifier.smtlib.SMTLibTranslator.visit(SMTLibTranslator.java:414)
        at ast.LogicalExpression.accept(LogicalExpression.java:69)
        at verifier.smtlib.SMTLibTranslator.visit(SMTLibTranslator.java:563)
        at ast.Ensure.accept(Ensure.java:21)
        at verifier.smtlib.SMTLibTranslator.visit(SMTLibTranslator.java:500)
        at ast.Function.accept(Function.java:34)
        at verifier.smtlib.SMTLibTranslator.visit(SMTLibTranslator.java:529)
        at ast.Program.accept(Program.java:40)
        at verifier.smtlib.SMTLibTranslator.getWPTree(SMTLibTranslator.java:73)
        at verifier.smtlib.z3.Z3.translate(Z3.java:32)
        at verifier.Verifier.call(Verifier.java:36)
        at verifier.VerifierInterface.verify(VerifierInterface.java:28)
        at misc.ExecutionHandler.verify(ExecutionHandler.java:135)
        at gui.controller.MainController.widgetSelected(MainController.java:268)
        at org.eclipse.swt.widgets.TypedListener.handleEvent(Unknown Source)
        at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
        at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
        at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
        at gui.MainFrame.openWindow(MainFrame.java:256)
        at gui.controller.MainController.initMainFrame(MainController.java:97)
        at gui.controller.MainController.<init>(MainController.java:85)
        at misc.MainClass.main(MainClass.java:18)

**Comment by danielgrahl** [comment]
Arrays seem to be the problem.

**Comment by ratefuchs** [comment]
not arrays itself, but the length function (which is implicitly used on array reads, also).

**Comment by janhaag** [comment]
This issue is somewhat unspecific. Issues #42, #43 and #44 replace it.
