### ISSUE TITLE
give more helpful error messages on syntax error

### ISSUE THREAD

**Issue by danielgrahl** [janhaag/PSE2011#11]
The following program gives the error message "AST creation not possible!" which is not helping, also the line number is given as -1.
main () {bool z = (0 < i && i <= length(a)); }

**Comment by janhaag** [comment]
This triggers a NPException in the parser. The correct version, however, doesn't.

**Comment by ratefuchs** [comment]
problem seems to be the same like in the simpler statement

int i = 2+;

It is missing the second operand and gets problems when adding null to the divisor list.
("a && b" is recognized as "a & $operand 2, which is missing$ & b")

Stacktrace:
        at java.util.LinkedList.addAll(LinkedList.java:269)
    at java.util.LinkedList.addAll(LinkedList.java:247)
    at parser.WhileLanguageParser.mul_expression(WhileLanguageParser.java:2970)
    at parser.WhileLanguageParser.add_expression(WhileLanguageParser.java:2789)
    at parser.WhileLanguageParser.rel_expression(WhileLanguageParser.java:2635)
    at parser.WhileLanguageParser.expression(WhileLanguageParser.java:2529)
    at parser.WhileLanguageParser.variable_declaration(WhileLanguageParser.java:1902)
    at parser.WhileLanguageParser.statement(WhileLanguageParser.java:1090)
    at parser.WhileLanguageParser.main_body(WhileLanguageParser.java:760)
    at parser.WhileLanguageParser.main(WhileLanguageParser.java:400)
    at parser.WhileLanguageParser.program(WhileLanguageParser.java:192)
    at parser.ParserInterface.parseProgram(ParserInterface.java:41)

**Comment by janhaag** [comment]
I fixed the NPExceptions, now this we correctly report the spurious '&' as well as 'i' not being declared.
