### ISSUE TITLE
ClassCastException after declaring a variable like an array

### ISSUE THREAD

**Issue by ratefuchs** [janhaag/PSE2011#18]
When parsing the program "main() { int i = array; }", the application crashes with the following stack trace:

Exception in thread "main" java.lang.ClassCastException: ast.IntegerType cannot be cast to ast.ArrayType
    at interpreter.Scope.createArray(Scope.java:246)
    at parser.TypeChecker.visit(TypeChecker.java:595)
    at ast.ArrayDeclaration.accept(ArrayDeclaration.java:39)
    at parser.TypeChecker.visit(TypeChecker.java:668)
    at ast.StatementBlock.accept(StatementBlock.java:30)
    at parser.TypeChecker.visit(TypeChecker.java:384)
    at ast.Function.accept(Function.java:34)
    at parser.TypeChecker.visit(TypeChecker.java:411)
    at ast.Program.accept(Program.java:40)
    at parser.TypeChecker.checkTypes(TypeChecker.java:40)
    at parser.ParserInterface.parseProgram(ParserInterface.java:47)
    at misc.ExecutionHandler.parse(ExecutionHandler.java:49)
    at gui.controller.MainController.widgetSelected(MainController.java:265)
    at org.eclipse.swt.widgets.TypedListener.handleEvent(Unknown Source)
    at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
    at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
    at gui.MainFrame.openWindow(MainFrame.java:256)
    at gui.controller.MainController.initMainFrame(MainController.java:97)
    at gui.controller.MainController.<init>(MainController.java:85)
    at misc.MainClass.main(MainClass.java:18)

**Comment by ratefuchs** [comment]
The bug is already fixed, the type checker now prevents this crash.
However, since the program is not correct, the type check fails and an appropriate error message is given.
