### ISSUE TITLE
no verification with arrays

### ISSUE THREAD

**Issue by danielgrahl** [janhaag/PSE2011#21]
as above, yields something like
java.lang.NullPointerException
        at verifier.smtlib.SMTLibTranslator.getMangledArrayName(SMTLibTranslator.java:660)
        at verifier.smtlib.SMTLibTranslator.visit(SMTLibTranslator.java:478)
        at ast.ArrayRead.accept(ArrayRead.java:37)
        at verifier.smtlib.SMTLibTranslator.visit(SMTLibTranslator.java:390)
        at ast.LogicalExpression.accept(LogicalExpression.java:69)

**Comment by linjin** [comment]
Fixed together with issue 22 in 2ff67567d8e08e3fc05cb67de63c7031be2343c9
