### ISSUE TITLE
NullPointerException after running program with statement breakpoint on last line

### ISSUE THREAD

**Issue by syras** [janhaag/PSE2011#33]
When you execute this program 

main() {
int i = 2; //<-- statement breakpoint on this line!
}

the following exception is displayed:

Exception in thread "Thread-1" java.lang.NullPointerException
    at interpreter.ProgramExecution.checkBreakpoints(ProgramExecution.java:151)
    at misc.ExecutionHandler.run(ExecutionHandler.java:80)
    at gui.controller.MainController$1.run(MainController.java:194)

**Comment by linjin** [comment]
this is fixed in de399f76fa98fdf62537ca003ace3aff8bb5fade
