### ISSUE TITLE
NPException on function calls

### ISSUE THREAD

**Issue by ratefuchs** [janhaag/PSE2011#39]
When trying to parse the following (correct!) program:

bool f(){return true;}
main(){assert f();}

the following exception occurs:
java.lang.NullPointerException
    at java.util.LinkedList.addAll(LinkedList.java:269)
    at java.util.LinkedList.addAll(LinkedList.java:247)
    at parser.WhileLanguageParser.qe_helper(WhileLanguageParser.java:2441)
    at parser.WhileLanguageParser.quantified_expression(WhileLanguageParser.java:2311)
    at parser.WhileLanguageParser.assert_statement(WhileLanguageParser.java:1382)
    at parser.WhileLanguageParser.statement(WhileLanguageParser.java:1079)
    at parser.WhileLanguageParser.main_body(WhileLanguageParser.java:762)
    at parser.WhileLanguageParser.main(WhileLanguageParser.java:400)
    at parser.WhileLanguageParser.program(WhileLanguageParser.java:192)
    at parser.ParserInterface.parseProgram(ParserInterface.java:41)

**Comment by janhaag** [comment]
I'm not entirely sure why, but the parser fails to interpret this as a simple expression, trying to interpret 'f' as a quantifier instead (which is obviously wrong).

~~ sorry, hit the wrong button
