### ISSUE TITLE
Global breakpoints cannot be added

### ISSUE THREAD

**Issue by danielgrahl** [janhaag/PSE2011#5]

**Comment by linjin** [comment]
This is strange... It should be working regardless of OS. The only reason I can think of is that you may have tried e.g. i=2 instead of i==2? The first one won't work because it is not an expression.

**Comment by danielgrahl** [comment]
OK, it works with the correct syntax. BUT: it crashes when writing wrong syntax:
Exception in thread "main" java.lang.NullPointerException
        at gui.controller.TableViewController.widgetSelected(TableViewController.java:155)
        at org.eclipse.swt.widgets.TypedListener.handleEvent(Unknown Source)
        at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
        at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
        at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
        at gui.MainFrame.openWindow(MainFrame.java:256)
        at gui.controller.MainController.initMainFrame(MainController.java:97)
        at gui.controller.MainController.<init>(MainController.java:85)
        at misc.MainClass.main(MainClass.java:18)

**Comment by linjin** [comment]
This is fixed here eee636bb67209661c1841a76814d2e612bd9b7a3

**Comment by linjin** [comment]
The program still crashes when trying to add e.g. i-- or quantified expressions
