### ISSUE TITLE
Still NPExceptions in parser

### ISSUE THREAD

**Issue by ratefuchs** [janhaag/PSE2011#70]
Parsing the following program

main(){int a[] = array[2];}

leads to the following stack trace:

java.lang.NullPointerException
    at java.util.LinkedList.addAll(LinkedList.java:269)
    at java.util.LinkedList.addAll(LinkedList.java:247)
    at parser.WhileLanguageParser.assignment(WhileLanguageParser.java:1793)
    at parser.WhileLanguageParser.statement(WhileLanguageParser.java:1119)
    at parser.WhileLanguageParser.main_body(WhileLanguageParser.java:762)
    at parser.WhileLanguageParser.main(WhileLanguageParser.java:400)
    at parser.WhileLanguageParser.program(WhileLanguageParser.java:192)
    at parser.ParserInterface.parseProgram(ParserInterface.java:41)

**Comment by janhaag** [comment]
I've factored out the two reports into separate bugs (#86 and #87) and deleted the comments.

**Comment by janhaag** [comment]
I can't reproduce this on HEAD
