### ISSUE TITLE
IllegalStateException when trying to use function call as array index

### ISSUE THREAD

**Issue by linjin** [janhaag/PSE2011#75]
The following program 

int foo() {
return 0;
}
main(int[] a) {
a[0] = a[foo()];
}

throws

Exception in thread "main" java.lang.IllegalStateException: Function may only be set once!
    at ast.FunctionCall.setFunction(FunctionCall.java:48)
    at parser.TypeChecker.visit(TypeChecker.java:268)
    at ast.FunctionCall.accept(FunctionCall.java:37)
    at parser.TypeChecker.visit(TypeChecker.java:191)
    at ast.LogicalExpression.accept(LogicalExpression.java:69)
        ...

**Comment by ratefuchs** [comment]
Problem seems to be the implicit bounds checking, where the function call is visited more than once (0 <= foo() & foo() < length). Solution is to allow setting the function more than once.
