### ISSUE TITLE
Incorrect axiom causes NPException in Typechecker

### ISSUE THREAD

**Issue by linjin** [janhaag/PSE2011#85]
The following program

axiom i;
main () {
}

throws

java.lang.NullPointerException
    at parser.TypeChecker.visit(TypeChecker.java:291)
    at ast.VariableRead.accept(VariableRead.java:77)
    at parser.TypeChecker.visit(TypeChecker.java:457)
    at ast.Axiom.accept(Axiom.java:21)
    at parser.TypeChecker.visit(TypeChecker.java:375)
    at ast.Program.accept(Program.java:40)

**Comment by ratefuchs** [comment]
Forgot to set current scope so it was null (happens only if you try to access variables not in quantified expression).
