### ISSUE TITLE
NPException in Parser

### ISSUE THREAD

**Issue by janhaag** [janhaag/PSE2011#86]
The following program throws a NPException:

main() {
assert a
}

java.lang.NullPointerException
at java.util.LinkedList.addAll(Unknown Source)
at java.util.LinkedList.addAll(Unknown Source)
at parser.WhileLanguageParser.qe_helper(WhileLanguageParser.java:2441)
at parser.WhileLanguageParser.quantified_expression(WhileLanguageParser.java:2311)
at parser.WhileLanguageParser.assert_statement(WhileLanguageParser.java:1382)
at parser.WhileLanguageParser.statement(WhileLanguageParser.java:1079)

**Comment by janhaag** [comment]
I can't reproduce this on HEAD.
